sprint 1 test cases

diff --git a/goss-testing/tests/iuf/goss-iuf-invalid-media.yaml b/goss-testing/tests/iuf/goss-iuf-invalid-media.yaml
--- a/goss-testing/tests/iuf/goss-iuf-invalid-media.yaml
+++ b/goss-testing/tests/iuf/goss-iuf-invalid-media.yaml
@@ -37,14 +37,21 @@ command:
       desc: Run IUF with a media-dir which does not exist.
       sev: 0
     exec: |-
+      # Run pre-checks for IUF
       "{{$logrun}}" -l "{{$testlabel}}" \
       "{{$iuf_pre_checks}}" "{{ index $pre_checks 0 }}" "{{ index $pre_checks 1 }}" "{{ index $pre_checks 2 }}" && \
-      "{{$logrun}}" -l "{{$testlabel}}" /usr/bin/iuf -a "{{ index $activity 0 }}" -m "{{$media_dir}}" run -rv "{{$media_dir}}/product_vars.yaml" -r process-media && \
+
+      # Run IUF activity
+      "{{$logrun}}" -l "{{$testlabel}}" /usr/bin/iuf -a "{{ index $activity 0 }}" -m "{{$media_dir}}" run -rv "{{$media_dir}}/product_vars.yaml" -r process-media
+      run_exit_code=$?
+
+      # Run cleanup step independently
+      "{{$logrun}}" -l "{{$testlabel}}" "{{$iuf_cleanup}}" "{{ index $activity 0 }}"
+
+      # Exit with code 1 if the iuf_run command failed with exit code 1
+      if [ $run_exit_code -eq 1 ]; then
+        exit 1
+      fi
     exit-status: 1
     timeout: 50000
-    skip: false
-    exec: |-
-      "{{$logrun}}" -l "{{$testlabel}}" "{{$iuf_cleanup}}" "{{ index $activity 0 }}"
-    exit-status: 0
-    timeout: 10000
     skip: false
