sprint 2

diff --git a/goss-testing/tests/iuf/goss-iuf-no-media.yaml b/goss-testing/tests/iuf/goss-iuf-no-media.yaml
--- a/goss-testing/tests/iuf/goss-iuf-no-media.yaml
+++ b/goss-testing/tests/iuf/goss-iuf-no-media.yaml
@@ -37,18 +37,22 @@ command:
       desc: Run IUF without media-dir .
       sev: 0
     exec: |-
-      "{{$logrun}}" -l "{{$testlabel}}" \
-      "{{$iuf_pre_checks}}" "{{ index $pre_checks 0 }}" "{{ index $pre_checks 1 }}" "{{ index $pre_checks 2 }}" && \
-      "{{$logrun}}" -l "{{$testlabel}}" /usr/bin/iuf -a "{{ index $activity 0 }}" run -rv "{{$media_dir}}/product_vars.yaml" -r process-media
-      run_exit_code=$?
+      "{{$logrun}}" -l "{{$testlabel}}" bash -c '
+        # Run pre-checks for IUF
+        "{{$iuf_pre_checks}}" "{{ index $pre_checks 0 }}" "{{ index $pre_checks 1 }}" "{{ index $pre_checks 2 }}" "{{ index $pre_checks 3 }}" "{{ index $pre_checks 4 }}" "{{ index $pre_checks 5 }}" && \
 
-      # Run cleanup step independently
-      "{{$logrun}}" -l "{{$testlabel}}" "{{$iuf_cleanup}}" "{{ index $activity 0 }}"
+        # Run IUF
+        /usr/bin/iuf -a "{{ index $activity 0 }}" run -rv "{{$media_dir}}/product_vars.yaml" -r process-media
+        run_exit_code=$?
 
-      # Exit with code 1 if the iuf_run command failed with exit code 1
-      if [ $run_exit_code -eq 1 ]; then
-        exit 1
-      fi
+        # Run cleanup step
+        "{{$iuf_cleanup}}" "{{ index $activity 0 }}"
+
+        # Exit with code 1 if the iuf_run command failed
+        if [ $run_exit_code -eq 1 ]; then
+          exit 1
+        fi
+      '
     exit-status: 1
     timeout: 50000
     skip: false
