sprint 1 test cases

diff --git a/goss-testing/tests/iuf/goss-iuf-invalid-activity.yaml b/goss-testing/tests/iuf/goss-iuf-invalid-activity.yaml
--- a/goss-testing/tests/iuf/goss-iuf-invalid-activity.yaml
+++ b/goss-testing/tests/iuf/goss-iuf-invalid-activity.yaml
@@ -35,17 +35,26 @@ command:
   {{$testlabel}}:
     title: invalid activity name for IUF run
     meta:
-      desc: The output of IUF id invalid activity name is used.
+      desc: The output of IUF if invalid activity name is used.
       sev: 0
     exec: |-
+      # Run pre-checks
       "{{$logrun}}" -l "{{$testlabel}}" \
       "{{$iuf_pre_checks}}" "{{ index $pre_checks 0 }}" "{{ index $pre_checks 1 }}" "{{ index $pre_checks 2 }}" && \
+      
+      # Run the main IUF run step and check for exit code 1
       "{{$logrun}}" -l "{{$testlabel}}" "{{$iuf_run}}" "{{$media_dir}}" "{{ index $activity 1 }}"
+      
+      # Capture the exit code of the iuf_run step
+      run_exit_code=$?
+
+      # Run cleanup step independently
+      "{{$logrun}}" -l "{{$testlabel}}" "{{$iuf_cleanup}}" "{{ index $activity 1 }}"
+
+      # Exit with code 1 if the iuf_run command failed with exit code 1
+      if [ $run_exit_code -eq 1 ]; then
+        exit 1
+      fi
     exit-status: 1
     timeout: 180000
-    skip: false
-    exec: |-
-      "{{$logrun}}" -l "{{$testlabel}}" "{{$iuf_cleanup}}" "{{ index $activity 1 }}"
-    exit-status: 0
-    timeout: 10000
     skip: false
