Modify comparision of exit code with non-zero instead of exit-code 1 as we need to consider all non-zero exit code as error

diff --git a/goss-testing/tests/ncn/goss-iuf-activity-list-stages.yaml b/goss-testing/tests/ncn/goss-iuf-activity-list-stages.yaml
--- a/goss-testing/tests/ncn/goss-iuf-activity-list-stages.yaml
+++ b/goss-testing/tests/ncn/goss-iuf-activity-list-stages.yaml
@@ -54,9 +54,9 @@ command:
           # Run cleanup step independently
           "{{$iuf_cleanup}}" "{{ index $activity 0 }}"
 
-          # Exit with code 1 if the iuf ls command failed with exit code 1
-          if [ $run_exit_code -eq 1 ]; then
-            exit 1
+          # Exit with non-zero exit code if the iuf ls command failed with non-zero exit code
+          if [ $run_exit_code -ne 0 ]; then
+            exit $run_exit_code
           fi
         '
     exit-status: 0
diff --git a/goss-testing/tests/ncn/goss-iuf-activity-resume.yaml b/goss-testing/tests/ncn/goss-iuf-activity-resume.yaml
--- a/goss-testing/tests/ncn/goss-iuf-activity-resume.yaml
+++ b/goss-testing/tests/ncn/goss-iuf-activity-resume.yaml
@@ -51,9 +51,9 @@ command:
           # Cleanup the workflows,log and media dir
           "{{$iuf_cleanup}}"
 
-          # Exit with code 1 if the iuf command failed with exit code 1
-          if [ $run_exit_code -eq 1 ]; then
-            exit 1
+          # Exit with non-zero exit code if the iuf command failed with non-zero exit code
+          if [ $run_exit_code -ne 0 ]; then
+            exit $run_exit_code
           fi
         '
     exit-status: 0
