[Backport release/1.3] CASMINST-5224: handle special password character and fix exit code (#381)
CASMINST-5224: handle special password character and fix exit code

(cherry picked from commit 83f0db143079083c0df84716ce97edac93ff417e)

Co-authored-by: Bo Quan <bo.quan@hpe.com>

diff --git a/goss-testing/tests/ncn/goss-k8s-resolve-external-dns.yaml b/goss-testing/tests/ncn/goss-k8s-resolve-external-dns.yaml
--- a/goss-testing/tests/ncn/goss-k8s-resolve-external-dns.yaml
+++ b/goss-testing/tests/ncn/goss-k8s-resolve-external-dns.yaml
@@ -29,7 +29,7 @@ command:
       sev: 0
     exec: |-
           # External DNS resolution is best tested by checking if the configured LDAP server is pingable.
-          # Pass if the test requirements are not met:
+          # Fail if the test requirements are not met:
           # - Unbound forward-addr is not configured.
           # - LDAP providerId is not configured.
           # Fail if the LDAP providerId is configured but the LDAP connectionURL is not.
@@ -40,7 +40,7 @@ command:
               MASTER_USERNAME=$(kubectl get secret -n services keycloak-master-admin-auth -ojsonpath='{.data.user}' | base64 -d)
               MASTER_PASSWORD=$(kubectl get secret -n services keycloak-master-admin-auth -ojsonpath='{.data.password}' | base64 -d)
 
-              curl -ks -d client_id=admin-cli -d username=$MASTER_USERNAME -d password=$MASTER_PASSWORD \
+              curl -ks -d client_id=admin-cli -d username=$MASTER_USERNAME --data-urlencode password="$MASTER_PASSWORD" \
                    -d grant_type=password https://api-gw-service-nmn.local/keycloak/realms/master/protocol/openid-connect/token | jq -r '.access_token'; 
            }
    
@@ -52,12 +52,12 @@ command:
 
            if [[ ! $FORWARD_ADDR ]]; then 
               echo "Unbound must be configured for this test."
-              exit 0
+              exit 1
            fi
 
            if [[ ! $LDAP_PROVIDER ]]; then 
               echo "LDAP must be configured for this test."
-              exit 0
+              exit 1
            fi
 
            echo "Unbound and LDAP are configured" 
