CASMPET-3996: Remove hard coded switch admin password from goss var files, and instead pass in password via environment variables.
Remove old and unused Goss tests that made use of the Switch password.

diff --git a/goss-testing/automated/livecd-provisioning-checks b/goss-testing/automated/livecd-provisioning-checks
--- a/goss-testing/automated/livecd-provisioning-checks
+++ b/goss-testing/automated/livecd-provisioning-checks
@@ -26,6 +26,11 @@ vars_file="/opt/cray/tests/install/livecd/vars/variables-livecd.yaml"
 nodes=$(cat /etc/dnsmasq.d/statics.conf | grep -ohE 'ncn-[m,w,s]([0-9]{3})' | awk '!a[$0]++')
 tmpvars=/tmp/goss-variables-$(date +%s)-temp.yaml
 
+if [[ -z "$SW_ADMIN_PASSWORD" ]]; then
+  echo "Error: Managment switch admin password not provided via SW_ADMIN_PASSWORD enviroment varaible."
+  exit 1
+fi
+
 # add node names from statics.conf to temp variables file
 if [ `echo $nodes | wc -w` -ne 0 ];then
   echo "nodes:" >> $tmpvars
diff --git a/goss-testing/automated/ncn-healthcheck b/goss-testing/automated/ncn-healthcheck
--- a/goss-testing/automated/ncn-healthcheck
+++ b/goss-testing/automated/ncn-healthcheck
@@ -23,6 +23,12 @@
 # GOSS_BASE isn't set by default on the NCNs, just on LiveCD
 [[ -z $GOSS_BASE ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"
 
+if [[ -z "$SW_ADMIN_PASSWORD" ]]; then
+  echo "ERROR Management switch admin password must be provided via the SW_ADMIN_PASSWORD enviroment varaible"
+  echo "Example: export SW_ADMIN_PASSWORD='changeme'"
+  exit 1
+fi
+
 $GOSS_BASE/automated/ncn-healthcheck-storage
 $GOSS_BASE/automated/ncn-healthcheck-master
 $GOSS_BASE/automated/ncn-healthcheck-worker
