CASMINST-5025: Create more shared functions for automated scripts; improve methods for determing NCN lists

diff --git a/goss-testing/automated/livecd-preflight-checks b/goss-testing/automated/livecd-preflight-checks
--- a/goss-testing/automated/livecd-preflight-checks
+++ b/goss-testing/automated/livecd-preflight-checks
@@ -29,16 +29,11 @@ set -e
 
 # GOSS_BASE should already be set on the PIT node, but just in case we
 # will set it here
-[[ -z $GOSS_BASE ]] && export GOSS_BASE="/opt/cray/tests/install/livecd"
+[[ -z ${GOSS_BASE} ]] && export GOSS_BASE="/opt/cray/tests/install/livecd"
 
 export GOSS_LOG_BASE_DIR=/opt/cray/tests/install/logs
 
-# Print an error message and exit
-function err_exit
-{
-    echo "ERROR: $*"
-    exit 1
-}
+source "${GOSS_BASE}/automated/run-ncn-tests.sh"
 
 # Validates that a file exists and is a regular file
 function file_exists
@@ -47,52 +42,32 @@ function file_exists
     [[ -f "$1" ]] || err_exit "File exists but is not a regular file: $1"
 }
 
-export GOSS_FILE="$GOSS_BASE/suites/livecd-preflight-tests.yaml"
-vars_file="$GOSS_BASE/vars/variables-livecd.yaml"
-dnsmasq_statics=/etc/dnsmasq.d/statics.conf
+export GOSS_FILE="${GOSS_BASE}/suites/livecd-preflight-tests.yaml"
 
-file_exists "$GOSS_FILE"
-file_exists "$vars_file"
-file_exists "$dnsmasq_statics"
+file_exists "${GOSS_FILE}"
 
-nodes=$(grep -ohE 'ncn-[msw]([0-9]{3})' "$dnsmasq_statics" | awk '!a[$0]++')
-tmpvars=/tmp/goss-variables-$(date +%s)-temp.yaml
-
-# Add node names from statics.conf to temp variables file.
-# We expect there to be at least 9 nodes (3 each of masters,
-# storage, and workers).
-num_nodes=$(echo $nodes | wc -w)
-if [[ $num_nodes -ge 9 ]];then
-  echo "nodes:" >> $tmpvars
-  for node in $nodes; do
-    echo "  - $node" >> $tmpvars    
-  done
-  echo "" >> $tmpvars
-elif [[ $num_nodes -eq 0 ]]; then
-  err_exit "Node names could not be found in $dnsmasq_statics file!"
-else
-  err_exit "Only $num_nodes node name(s) found in $dnsmasq_statics file!"
-fi
-cat $vars_file >> $tmpvars
+# The create_tmpvars_file function is defined in run-ncn-tests.sh
+# It creates the temporary variables file and saves the path to it in the ${tmpvars} variable
+create_tmpvars_file || exit 1
 
 echo $'\e[1;33m'Running LiveCD preflight checks \(may take a few minutes to complete\)...$'\e[0m'
 
 # Run the LiveCD preflight Goss test suite
-export GOSS_VARS=$tmpvars
+export GOSS_VARS=${tmpvars}
 set +e
 results=$(/usr/bin/goss validate -f json)
 set -e
 
-if ! `echo $results | jq -e > /dev/null 2>&1`; then
+if ! `echo ${results} | jq -e > /dev/null 2>&1`; then
   err_exit $'\e[1;31m'Output not valid JSON$'\e[0m'
 fi
 
-echo $results | jq -c '.results | sort_by(.result) | .[]' | while read -r test; do
-  result=$(echo $test | jq -r '.result')
+echo ${results} | jq -c '.results | sort_by(.result) | .[]' | while read -r test; do
+  result=$(echo ${test} | jq -r '.result')
 
-  if [ -z $result ]; then
+  if [[ -z ${result} ]]; then
     continue
-  elif [ $result == 0 ]; then
+  elif [[ ${result} == 0 ]]; then
     result=PASS
     echo $'\e[1;32m'
   else
@@ -100,35 +75,35 @@ echo $results | jq -c '.results | sort_by(.result) | .[]' | while read -r test; 
     echo $'\e[1;31m'
   fi
 
-  title=$(echo $test | jq -r '.title')
-  description=$(echo $test | jq -r '.meta.desc')
-  severity=$(echo $test | jq -r '.meta.sev')
-  summary=$(echo $test | jq -r '."summary-line"')
-  time=$(echo $test | jq -r '.duration')
-  time=$(echo "scale=8; $time/1000000000" | bc | awk '{printf "%.8f\n", $0}')
+  title=$(echo ${test} | jq -r '.title')
+  description=$(echo ${test} | jq -r '.meta.desc')
+  severity=$(echo ${test} | jq -r '.meta.sev')
+  summary=$(echo ${test} | jq -r '."summary-line"')
+  time=$(echo ${test} | jq -r '.duration')
+  time=$(echo "scale=8; ${time}/1000000000" | bc | awk '{printf "%.8f\n", $0}')
 
-  echo "Result: $result"
-  echo "Test Name: $title"
-  echo "Description: $description"
-  echo "Severity: $severity"
-  echo "Test Summary: $summary"
-  echo "Execution Time: $time seconds"
+  echo "Result: ${result}"
+  echo "Test Name: ${title}"
+  echo "Description: ${description}"
+  echo "Severity: ${severity}"
+  echo "Test Summary: ${summary}"
+  echo "Execution Time: ${time} seconds"
   echo "Node: ncn-m001"
 done
 
 echo $'\e[0m'
 
-total=$(echo $results | jq -r '.summary."test-count"')
-failed=$(echo $results | jq -r '.summary."failed-count"')
-time=$(echo $results | jq -r '.summary."total-duration"')
-time=$(echo "scale=4; $time/1000000000" | bc | awk '{printf "%.4f\n", $0}')
+total=$(echo ${results} | jq -r '.summary."test-count"')
+failed=$(echo ${results} | jq -r '.summary."failed-count"')
+time=$(echo ${results} | jq -r '.summary."total-duration"')
+time=$(echo "scale=4; ${time}/1000000000" | bc | awk '{printf "%.4f\n", $0}')
 
-echo "Total Tests: $total, Total Passed: $((total-failed)), Total Failed: $failed, Total Execution Time: $time seconds"
+echo "Total Tests: ${total}, Total Passed: $((total-failed)), Total Failed: ${failed}, Total Execution Time: ${time} seconds"
 echo
 
-if [[ $total -eq 0 ]]; then
+if [[ ${total} -eq 0 ]]; then
     err_exit "No tests were run!"
-elif [[ $failed -ne 0 ]]; then
+elif [[ ${failed} -ne 0 ]]; then
     err_exit "Not all tests passed"
 fi
 echo "All tests passed!"
diff --git a/goss-testing/automated/livecd-provisioning-checks b/goss-testing/automated/livecd-provisioning-checks
--- a/goss-testing/automated/livecd-provisioning-checks
+++ b/goss-testing/automated/livecd-provisioning-checks
@@ -24,46 +24,35 @@
 
 # GOSS_BASE should already be set on the PIT node, but just in case we
 # will set it here
-[[ -z $GOSS_BASE ]] && export GOSS_BASE="/opt/cray/tests/install/livecd"
+[[ -z ${GOSS_BASE} ]] && export GOSS_BASE="/opt/cray/tests/install/livecd"
 
 export GOSS_LOG_BASE_DIR=/opt/cray/tests/install/logs
 
-export GOSS_FILE="$GOSS_BASE/suites/livecd-provisioning-tests.yaml"
-vars_file="$GOSS_BASE/vars/variables-livecd.yaml"
+source "${GOSS_BASE}/automated/run-ncn-tests.sh"
 
-nodes=$(cat /etc/dnsmasq.d/statics.conf | grep -ohE 'ncn-[msw]([0-9]{3})' | awk '!a[$0]++')
-tmpvars=/tmp/goss-variables-$(date +%s)-temp.yaml
+export GOSS_FILE="${GOSS_BASE}/suites/livecd-provisioning-tests.yaml"
 
-# add node names from statics.conf to temp variables file
-if [ `echo $nodes | wc -w` -ne 0 ];then
-  echo "nodes:" >> $tmpvars
-  for node in $nodes; do
-    echo "  - $node" >> $tmpvars
-    echo "" >> $tmpvars
-  done
-else
-  echo "Node names could not be found in statics.conf file! Exiting now."
-  exit 1
-fi
-cat $vars_file >> $tmpvars
+# The create_tmpvars_file function is defined in run-ncn-tests.sh
+# It creates the temporary variables file and saves the path to it in the ${tmpvars} variable
+create_tmpvars_file || exit 1
 
 echo $'\e[1;33m'Running LiveCD provisioning checks \(may take a few minutes to complete\)...$'\e[0m'
 
 # Run the LiveCD provisioning Goss test suite
-export GOSS_VARS=$tmpvars
+export GOSS_VARS=${tmpvars}
 results=$(/usr/bin/goss validate -f json)
 
-if ! `echo $results | jq -e > /dev/null 2>&1`; then
+if ! `echo ${results} | jq -e > /dev/null 2>&1`; then
   echo $'\e[1;31m'ERROR: Output not valid JSON$'\e[0m'
   exit 1
 fi
 
-echo $results | jq -c '.results | sort_by(.result) | .[]' | while read -r test; do
-  result=$(echo $test | jq -r '.result')
+echo ${results} | jq -c '.results | sort_by(.result) | .[]' | while read -r test; do
+  result=$(echo ${test} | jq -r '.result')
 
-  if [ -z $result ]; then
+  if [ -z ${result} ]; then
     continue
-  elif [ $result == 0 ]; then
+  elif [ ${result} == 0 ]; then
     result=PASS
     echo $'\e[1;32m'
   else
@@ -71,29 +60,29 @@ echo $results | jq -c '.results | sort_by(.result) | .[]' | while read -r test; 
     echo $'\e[1;31m'
   fi
 
-  title=$(echo $test | jq -r '.title')
-  description=$(echo $test | jq -r '.meta.desc')
-  severity=$(echo $test | jq -r '.meta.sev')
-  summary=$(echo $test | jq -r '."summary-line"')
-  time=$(echo $test | jq -r '.duration')
-  time=$(echo "scale=8; $time/1000000000" | bc | awk '{printf "%.8f\n", $0}')
+  title=$(echo ${test} | jq -r '.title')
+  description=$(echo ${test} | jq -r '.meta.desc')
+  severity=$(echo ${test} | jq -r '.meta.sev')
+  summary=$(echo ${test} | jq -r '."summary-line"')
+  time=$(echo ${test} | jq -r '.duration')
+  time=$(echo "scale=8; ${time}/1000000000" | bc | awk '{printf "%.8f\n", $0}')
 
-  echo "Result: $result"
-  echo "Test Name: $title"
-  echo "Description: $description"
-  echo "Severity: $severity"
-  echo "Test Summary: $summary"
-  echo "Execution Time: $time seconds"
+  echo "Result: ${result}"
+  echo "Test Name: ${title}"
+  echo "Description: ${description}"
+  echo "Severity: ${severity}"
+  echo "Test Summary: ${summary}"
+  echo "Execution Time: ${time} seconds"
   echo "Node: ncn-m001"
 done
 
 echo $'\e[0m'
 
-total=$(echo $results | jq -r '.summary."test-count"')
-failed=$(echo $results | jq -r '.summary."failed-count"')
-time=$(echo $results | jq -r '.summary."total-duration"')
-time=$(echo "scale=4; $time/1000000000" | bc | awk '{printf "%.4f\n", $0}')
+total=$(echo ${results} | jq -r '.summary."test-count"')
+failed=$(echo ${results} | jq -r '.summary."failed-count"')
+time=$(echo ${results} | jq -r '.summary."total-duration"')
+time=$(echo "scale=4; ${time}/1000000000" | bc | awk '{printf "%.4f\n", $0}')
 
-echo "Total Tests: $total, Total Passed: $((total-failed)), Total Failed: $failed, Total Execution Time: $time seconds"
+echo "Total Tests: ${total}, Total Passed: $((total-failed)), Total Failed: ${failed}, Total Execution Time: ${time} seconds"
 
 exit
diff --git a/goss-testing/automated/ncn-preflight-checks b/goss-testing/automated/ncn-preflight-checks
--- a/goss-testing/automated/ncn-preflight-checks
+++ b/goss-testing/automated/ncn-preflight-checks
@@ -23,25 +23,28 @@
 # OTHER DEALINGS IN THE SOFTWARE.
 
 # GOSS_BASE isn't set by default on the NCNs, just on LiveCD
-[[ -z $GOSS_BASE ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"
+[[ -z ${GOSS_BASE} ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"
 
 export GOSS_LOG_BASE_DIR=/opt/cray/tests/install/logs
 
-source "$GOSS_BASE/automated/run-ncn-tests.sh"
+source "${GOSS_BASE}/automated/run-ncn-tests.sh"
 
 echo $'\e[1;33m'NCN Preflight Checks$'\e[0m'
 echo $'\e[1;33m'--------------------$'\e[0m'
 
-if [ ! -f "/etc/dnsmasq.d/statics.conf" ]; then
-  echo "ERROR: These tests can only be run from the LiveCD."
-  exit 1
+if ! is_pit_node ; then
+    err_exit "These tests can only be run from the LiveCD."
 fi
 
-# find the ncn node names and query the server endpoint
-nodes=$(grep -ohE "ncn-[msw]([0-9]{3})" /etc/dnsmasq.d/statics.conf | grep -v ncn-m001 | awk '!a[$0]++')
+# Find the NCN node names and query the server endpoint
+# The get_ncns function is defined in run-ncn-tests.sh
+nodes=$(get_ncns --exclude-pit) || exit 1
 
-for node in $nodes; do
-  run_ncn_tests $node 8995 ncn-preflight-tests
+# The get_ncns function should always give NCNs if its return code was 0, but better safe than sorry
+[[ -n ${nodes} ]] || err_exit "No NCNs found"
+
+for node in ${nodes}; do
+    run_ncn_tests "${node}" 8995 ncn-preflight-tests
 done
 
 exit
