more updates

diff --git a/goss-testing/automated/ncn-kubernetes-checks b/goss-testing/automated/ncn-kubernetes-checks
--- a/goss-testing/automated/ncn-kubernetes-checks
+++ b/goss-testing/automated/ncn-kubernetes-checks
@@ -21,32 +21,38 @@
 # ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 # OTHER DEALINGS IN THE SOFTWARE.
 
+function run_k8s_tests {
+  type=$1
+  node=$2
+  port=$3
+  endpoint=$4
+  echo Running tests against NCN Kubernetes $type node $'\e[1;33m'$node$'\e[0m'
+  url=http://$node:$port/$endpoint
+  echo Server Endpoint: $url
+  results=`curl -s {$url}`
+  if [[ $? == 0 ]]; then
+    echo
+    echo "TEST OUTPUT:"
+    echo $results | jq
+  else
+    echo $'\e[1;31m'ERROR: Server endpoint could not be reached$'\e[0m'
+  fi
+}
+
 # master nodes
-nodes="ncn-m002,ncn-m003"
-endpoint="ncn-kubernetes-tests-master"
-port=8996
-
-IFS=',' read -ra nodes <<< "$nodes"
-
-for node in "${nodes[@]}"
-do
-  echo "Running tests against NCN Kubernetes master node: $node"
-  results=`curl -s http://{$node}:{$port}/{$endpoint}`
-  echo $results | jq
-done
+echo $'\e[1;33m'Master Node Kubernetes Tests$'\e[0m'
+echo $'\e[1;33m'----------------------------$'\e[0m'
+echo
+# find the master node names and query the server endpoint
+grep NMN /etc/dnsmasq.d/statics.conf | grep ncn-m | grep -v ncn-m001 | awk -F"," '{print $5}' | \
+  while read node ; do run_k8s_tests "master" "$node" "8996" "ncn-kubernetes-tests-master" echo ; done
 
 # worker nodes
-nodes="ncn-w001,ncn-w002,ncn-w003"
-endpoint="ncn-kubernetes-tests-worker"
-port=8998
-
-IFS=',' read -ra nodes <<< "$nodes"
-
-for node in "${nodes[@]}"
-do
-  echo "Running tests against NCN Kubernetes worker node: $node"
-  results=`curl -s http://{$node}:{$port}/{$endpoint}`
-  echo $results | jq
-done
+echo $'\e[1;33m'Worker Node Kubernetes Tests$'\e[0m'
+echo $'\e[1;33m'----------------------------$'\e[0m'
+echo
+# find the worker node names and query the server endpoint
+grep NMN /etc/dnsmasq.d/statics.conf | grep ncn-w | awk -F"," '{print $5}' | while read node ; \
+  do run_k8s_tests "worker" "$node" "8998" "ncn-kubernetes-tests-worker" echo ; done
 
 exit
diff --git a/goss-testing/automated/ncn-preflight-checks b/goss-testing/automated/ncn-preflight-checks
--- a/goss-testing/automated/ncn-preflight-checks
+++ b/goss-testing/automated/ncn-preflight-checks
@@ -21,17 +21,27 @@
 # ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 # OTHER DEALINGS IN THE SOFTWARE.
 
-nodes="ncn-s001,ncn-s002,ncn-s003,ncn-w001,ncn-w002,ncn-w003,ncn-m002,ncn-m003"
-IFS=',' read -ra nodes <<< "$nodes"
+function run_preflight_tests {
+  node=$1
+  port=$2
+  echo Running tests against node $'\e[1;33m'$node$'\e[0m'
+  url=http://$node:$port/ncn-preflight-tests
+  echo Server URL: $url
+  results=`curl -s {$url}`
+  if [[ $? == 0 ]]; then
+    echo
+    echo "TEST OUTPUT:"
+    echo $results | jq
+  else
+    echo $'\e[1;31m'ERROR: Server endpoint could not be reached$'\e[0m'
+  fi
+}
 
-port=8995
-endpoint="ncn-preflight-tests"
-
-for node in "${nodes[@]}"
-do
-  echo "Running tests on NCN node: $node"
-  results=`curl -s http://{$node}:{$port}/{$endpoint}`
-  echo $results | jq
-done
+echo $'\e[1;33m'NCN Preflight Automated Tests$'\e[0m'
+echo $'\e[1;33m'-----------------------------$'\e[0m'
+echo
+# find the ncn node names and query the server endpoint
+grep NMN /etc/dnsmasq.d/statics.conf | grep -v ncn-m001 | awk -F"," '{print $5}' | \
+  while read node ; do run_preflight_tests "$node" "8995" echo ; done
 
 exit
