final fixes

diff --git a/goss-testing/automated/ncn-preflight-checks b/goss-testing/automated/ncn-preflight-checks
--- a/goss-testing/automated/ncn-preflight-checks
+++ b/goss-testing/automated/ncn-preflight-checks
@@ -21,10 +21,18 @@
 # ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 # OTHER DEALINGS IN THE SOFTWARE.
 
+# GOSS_BASE isn't set by default on the NCNs, just on LiveCD
+[[ -z $GOSS_BASE ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"
+
 source $GOSS_BASE/automated/run-ncn-tests.sh
 
 echo $'\e[1;33m'NCN Preflight Checks$'\e[0m'
 echo $'\e[1;33m'--------------------$'\e[0m'
+
+if [ ! -f "/etc/dnsmasq.d/statics.conf" ]; then
+  echo "ERROR: These tests can only be run from the LiveCD."
+  exit 1
+fi
 
 # find the ncn node names and query the server endpoint
 cat /etc/dnsmasq.d/statics.conf | grep -ohE "ncn-[m,w,s]([0-9]{3})" | grep -v ncn-m001 | awk '!a[$0]++' | \
