Adding a condition in ncn-k8s-combined-healthcheck script from goss-test to know its called through iuf and return exit code 1 if there is a test case failure

diff --git a/goss-testing/automated/ncn-k8s-combined-healthcheck b/goss-testing/automated/ncn-k8s-combined-healthcheck
--- a/goss-testing/automated/ncn-k8s-combined-healthcheck
+++ b/goss-testing/automated/ncn-k8s-combined-healthcheck
@@ -92,6 +92,12 @@ else
     rc=$?
 fi
 
+# Additional check to verify script is run from iuf hook script
+# To get original return code to validate goss-tests in iuf hook script
+if [[ -n "$1" && "$1" == "iuf" ]]; then
+    exit $rc
+fi
+
 # This script does not exit with non-0 return code just for test failures
 [[ $rc -le 1 ]] && exit 0
 exit 1
