CASMINST-5161: Only print Goss failures to screen (#355)

diff --git a/goss-testing/automated/ncn-healthcheck-worker b/goss-testing/automated/ncn-healthcheck-worker
--- a/goss-testing/automated/ncn-healthcheck-worker
+++ b/goss-testing/automated/ncn-healthcheck-worker
@@ -22,35 +22,20 @@
 # ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 # OTHER DEALINGS IN THE SOFTWARE.
 
-# GOSS_BASE isn't set by default on the NCNs, just on LiveCD
-[[ -z ${GOSS_BASE} ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"
+# Many functions and variables used in this script are defined/set/exported
+# in the run-ncn-tests.sh library
 
-export GOSS_LOG_BASE_DIR=/opt/cray/tests/install/logs
-
-vars_file="${GOSS_BASE}/vars/variables-ncn.yaml"
-
-source "${GOSS_BASE}/automated/run-ncn-tests.sh"
-
-echo $'\e[1;33m'NCN Run-Time Checks$'\e[0m'
+echo $'\e[1;33m'NCN Worker Run-Time Checks$'\e[0m'
 echo $'\e[1;33m'-------------------$'\e[0m'
+echo
 
-# The get_ncns function is defined in run-ncn-tests.sh
-if nodes=$(get_ncns --workers); then
-
-	# The get_ncns function should always give NCNs if its return code was 0, but better safe than sorry
-	if [[ -z ${nodes} ]]; then
-		print_error "No worker NCNs found"
-	else
-		# Query the server endpoints
-		for node in ${nodes} ; do
-			run_ncn_tests "${node}" "ncn-healthcheck-worker"
-			if ! is_pit_node ; then
-				run_ncn_tests "${node}" "ncn-afterpitreboot-healthcheck-worker"
-			fi
-		done
-	fi
-
-fi
+# The run-ncn-tests.sh library is located in the same directory as the
+# current script. Using dirname like this could produce a relative path,
+# but that's fine, since we just want to source this library script.
+# Note that this method is not infallible -- in particular, some symbolic
+# links can mess it up. But that won't be the case if this was installed
+# with the csm-testing RPM.
+source "$(dirname -- "$0")/run-ncn-tests.sh"
 
 # Specify the switch passwords and call the switch BGP neighbors tests.
 # This only needs to be done once on the NCN that this script is
@@ -58,18 +43,17 @@ fi
 # the cluster.
 # If explicit Aruba or Mellanox switch passwords were not provided, then go with SW_ADMIN_PASSWORD
 if [[ -z ${SW_ADMIN_PASSWORD} ]]; then
-	echo "ERROR Management switch admin password must be provided via the SW_ADMIN_PASSWORD enviroment varaible"
-	echo "Example: export SW_ADMIN_PASSWORD='changeme'"
-	exit 1
+    echo "ERROR Management switch admin password must be provided via the SW_ADMIN_PASSWORD enviroment varaible"
+    echo "Example: export SW_ADMIN_PASSWORD='changeme'"
+    exit 1
 fi
 
-# The create_tmpvars_file function is defined in run-ncn-tests.sh
-# It creates the temporary variables file and saves the path to it in the ${tmpvars} variable
-create_tmpvars_file "${vars_file}" || exit 1
+test_urls=$(ncn_healthcheck_worker_urls) || err_exit "Cannot find test URLs"
 
-echo $'\n\e[1;33m'---------------$'\e[0m'
-echo $'\e[1;33m'Switch BGP Neighbors$'\e[0m'
-echo "Test Name: goss-switch-bgp-neighbor-aruba-or-mellanox.yaml"
-echo "Description: Validates connection to the BGP neighbors of a switch. Check Admin Guide \"Check BGP Status and Reset Sessions\" for more details on how to fix this issue."
-goss -g "${GOSS_BASE}/tests/goss-switch-bgp-neighbor-aruba-or-mellanox.yaml" --vars "${tmpvars}" validate --format documentation
-exit $?
+run_goss_tests tests/goss-switch-bgp-neighbor-aruba-or-mellanox.yaml --format json | \
+    print_goss_json_results stdin ${test_urls}
+rc=$?
+
+# This script does not exit with non-0 return code just for test failures
+[[ $rc -le 1 ]] && exit 0
+exit 1
