fix for broken node connections

diff --git a/goss-testing/automated/ncn-storage-checks b/goss-testing/automated/ncn-storage-checks
--- a/goss-testing/automated/ncn-storage-checks
+++ b/goss-testing/automated/ncn-storage-checks
@@ -32,43 +32,44 @@ function run_storage_tests {
   echo Server URL: $url
   results=`curl -s {$url}`
 
-  if ! `echo $results | jq -e > /dev/null 2>&1`; then
-    echo $'\e[1;31m'ERROR: Output not valid JSON$'\e[0m'
-    return 1
-  fi
   if [[ $? == 0 ]]; then
-    echo $results | jq -c '.results | sort_by(.result) | .[]' | while read test; do
-      if ! `echo $test | jq '.result' > /dev/null 2>&1`; then
-        continue
-      else
-        result=`echo $test | jq '.result'`
-      fi
+    if ! `echo $results | jq -e > /dev/null 2>&1`; then
+      echo $'\e[1;31m'ERROR: Output not valid JSON$'\e[0m'
+      return 1
+    else
+      echo $results | jq -c '.results | sort_by(.result) | .[]' | while read test; do
+        if ! `echo $test | jq '.result' > /dev/null 2>&1`; then
+          continue
+        else
+          result=`echo $test | jq '.result'`
+        fi
 
-      if [ -z $result ]; then
-        continue
-      elif [ $result == 0 ]; then
-        result=PASS
-        echo $'\e[1;32m'
-      else
-        result=FAIL
-        echo $'\e[1;31m'
-      fi
+        if [ -z $result ]; then
+          continue
+        elif [ $result == 0 ]; then
+          result=PASS
+          echo $'\e[1;32m'
+        else
+          result=FAIL
+          echo $'\e[1;31m'
+        fi
 
-      title=`echo $test | jq -r '.title'`
-      description=`echo $test | jq -r '.meta.desc'`
-      severity=`echo $test | jq -r '.meta.sev'`
-      summary=`echo $test | jq -r '."summary-line"'`
-      time=`echo $test | jq -r '.duration'`
-      time=`echo "scale=8; $time/1000000000" | bc | awk '{printf "%.8f\n", $0}'`
+        title=`echo $test | jq -r '.title'`
+        description=`echo $test | jq -r '.meta.desc'`
+        severity=`echo $test | jq -r '.meta.sev'`
+        summary=`echo $test | jq -r '."summary-line"'`
+        time=`echo $test | jq -r '.duration'`
+        time=`echo "scale=8; $time/1000000000" | bc | awk '{printf "%.8f\n", $0}'`
 
-      echo "Result: $result"
-      echo "Test Name: $title"
-      echo "Description: $description"
-      echo "Severity: $severity"
-      echo "Test Summary: $summary"
-      echo "Execution Time: $time seconds"
-      echo "Node: $NODE"
-    done
+        echo "Result: $result"
+        echo "Test Name: $title"
+        echo "Description: $description"
+        echo "Severity: $severity"
+        echo "Test Summary: $summary"
+        echo "Execution Time: $time seconds"
+        echo "Node: $NODE"
+      done
+    fi
 
     echo $'\e[0m'
 
@@ -81,6 +82,7 @@ function run_storage_tests {
   else
     echo $'\e[1;31m'ERROR: Server endpoint could not be reached$'\e[0m'
   fi
+  return 0
 }
 
 echo $'\e[1;33m'Storage Node Automated Tests$'\e[0m'
