CASMINST-5161: Only print Goss failures to screen

diff --git a/goss-testing/automated/ncn-kubernetes-checks b/goss-testing/automated/ncn-kubernetes-checks
--- a/goss-testing/automated/ncn-kubernetes-checks
+++ b/goss-testing/automated/ncn-kubernetes-checks
@@ -22,81 +22,65 @@
 # ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 # OTHER DEALINGS IN THE SOFTWARE.
 
-# GOSS_BASE isn't set by default on the NCNs, just on LiveCD
-[[ -z ${GOSS_BASE} ]] && export GOSS_BASE=/opt/cray/tests/install/ncn
+# Many functions and variables used in this script are defined/set/exported
+# in the run-ncn-tests.sh library
 
-export GOSS_LOG_BASE_DIR=/opt/cray/tests/install/logs
-
-source "${GOSS_BASE}/automated/run-ncn-tests.sh"
-
-# file needed to run from livecd
-kube_creds=/root/.kube/config
-
-# is_pit_node is defined in run-ncn-tests.sh
-if is_pit_node; then
-  # running on a pit node
-  echo $'\e[1;33m'PIT Node Kubernetes Checks$'\e[0m'
-  echo $'\e[1;33m'--------------------------$'\e[0m'
-  if [[ -f ${kube_creds} ]]; then
-    # run livecd local Kubernetes cluster tests
-    k8s_local_tests
-  else
-    # We preface this warning with 'Total Tests:' to make it more visible, because the install documentation
-    # has the user grep for that string to review the results of the tests.
-    echo $'\e[1;31m'Total Tests: WARNING: Unable to run local Kubernetes checks because ${kube_creds} does not exist$'\e[0m'
-    echo
-  fi
-else
-  # run tests from an ncn
-  echo $'\e[1;33m'Kubernetes Cluster Node Checks$'\e[0m'
-  echo $'\e[1;33m'------------------------------$'\e[0m'
-  k8s_local_tests
-fi
-
-# master nodes
-echo $'\e[1;33m'Master Node Kubernetes Checks$'\e[0m'
-echo $'\e[1;33m'-----------------------------$'\e[0m'
-
-# The get_ncns function is defined in run-ncn-tests.sh
-if nodes=$(get_ncns --masters --exclude-pit); then
-
-	# The get_ncns function should always give NCNs if its return code was 0, but better safe than sorry
-	if [[ -z ${nodes} ]]; then
-		print_error "No master NCNs found"
-	else
-		# Query the server endpoints
-		for node in ${nodes} ; do
-			run_ncn_tests "${node}" "ncn-kubernetes-tests-master"
-			if ! is_pit_node ; then
-				run_ncn_tests "${node}" "ncn-afterpitreboot-kubernetes-tests-master"
-			fi
-		done
-	fi
-
-fi
-
+echo $'\e[1;33m'Kubernetes Checks$'\e[0m'
+echo $'\e[1;33m'------------------------------$'\e[0m'
 echo
 
-# worker nodes
-echo $'\e[1;33m'Worker Node Kubernetes Checks$'\e[0m'
-echo $'\e[1;33m'-----------------------------$'\e[0m'
+# The run-ncn-tests.sh library is located in the same directory as the
+# current script. Using dirname like this could produce a relative path,
+# but that's fine, since we just want to source thie library script.
+# Note that this method is not infallible -- in particular, some symbolic
+# links can mess it up. But that won't be the case if this was installed
+# with the csm-testing RPM.
+source "$(dirname -- "$0")/run-ncn-tests.sh"
 
-# The get_ncns function is defined in run-ncn-tests.sh
-if nodes=$(get_ncns --workers); then
+# Get master and worker node URLs
+master_nodes=$(get_ncns --masters --exclude-pit) ||
+    err_exit "Unable to get list of master nodes"
+worker_nodes=$(get_ncns --workers) ||
+    err_exit "Unable to get list of worker nodes"
 
-	# The get_ncns function should always give NCNs if its return code was 0, but better safe than sorry
-	if [[ -z ${nodes} ]]; then
-		print_error "No worker NCNs found"
-	else
-		# Query the server endpoints
-		for node in ${nodes} ; do
-			run_ncn_tests "${node}" "ncn-kubernetes-tests-worker"
-			if ! is_pit_node ; then
-				run_ncn_tests "${node}" "ncn-afterpitreboot-kubernetes-tests-worker"
-			fi
-		done
-	fi
+# Add k8s test endpoints
+master_test_urls=$(goss_endpoint_urls "ncn-kubernetes-tests-master" ${master_nodes}) ||
+    err_exit "Error finding test URLs for ncn-kubernetes-tests-master"
+worker_test_urls=$(goss_endpoint_urls "ncn-kubernetes-tests-worker" ${worker_nodes}) ||
+    err_exit "Error finding test URLs for ncn-kubernetes-tests-worker"
 
+if is_pit_node ; then
+    # running on a pit node
+
+    # file needed to run from livecd
+    kube_creds=/root/.kube/config
+
+    if is_nonempty_file "${kube_creds}"; then
+        # run livecd local Kubernetes cluster tests
+        run_goss_tests suites/common-kubernetes-tests-cluster.yaml --format json | \
+            print_goss_json_results stdin ${master_test_urls} ${worker_test_urls}
+        rc=$?
+    else
+        echo
+        echo $'\e[1;31m'WARNING: Unable to run local Kubernetes checks because ${kube_creds} does not exist or is invalid$'\e[0m'
+        print_goss_json_results stdin ${test_urls}
+        rc=$?
+    fi
+else
+    # run tests from an NCN
+
+    # If not running on the PIT node, this should mean we are post-PIT-reboot, so add in the appropriate tests
+    post_pit_master_test_urls=$(goss_endpoint_urls "ncn-afterpitreboot-kubernetes-tests-master" ${master_nodes}) ||
+        err_exit "Error finding test URLs for ncn-afterpitreboot-kubernetes-tests-master"
+
+    post_pit_worker_test_urls=$(goss_endpoint_urls "ncn-afterpitreboot-kubernetes-tests-worker" ${worker_nodes}) ||
+        err_exit "Error finding test URLs for ncn-afterpitreboot-kubernetes-tests-worker"
+
+    run_goss_tests suites/ncn-kubernetes-tests-cluster.yaml --format json | \
+        print_goss_json_results stdin ${master_test_urls} ${post_pit_master_test_urls} ${worker_test_urls} ${post_pit_worker_test_urls}
+    rc=$?
 fi
 
-exit
+# This script does not exit with non-0 return code just for test failures
+[[ $rc -le 1 ]] && exit 0
+exit 1
diff --git a/goss-testing/automated/ncn-preflight-checks b/goss-testing/automated/ncn-preflight-checks
--- a/goss-testing/automated/ncn-preflight-checks
+++ b/goss-testing/automated/ncn-preflight-checks
@@ -22,15 +22,20 @@
 # ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 # OTHER DEALINGS IN THE SOFTWARE.
 
-# GOSS_BASE isn't set by default on the NCNs, just on LiveCD
-[[ -z ${GOSS_BASE} ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"
-
-export GOSS_LOG_BASE_DIR=/opt/cray/tests/install/logs
-
-source "${GOSS_BASE}/automated/run-ncn-tests.sh"
+# Many functions and variables used in this script are defined/set/exported
+# in the run-ncn-tests.sh library
 
 echo $'\e[1;33m'NCN Preflight Checks$'\e[0m'
 echo $'\e[1;33m'--------------------$'\e[0m'
+echo
+
+# The run-ncn-tests.sh library is located in the same directory as the
+# current script. Using dirname like this could produce a relative path,
+# but that's fine, since we just want to source thie library script.
+# Note that this method is not infallible -- in particular, some symbolic
+# links can mess it up. But that won't be the case if this was installed
+# with the csm-testing RPM.
+source "$(dirname -- "$0")/run-ncn-tests.sh"
 
 if ! is_pit_node ; then
     err_exit "These tests can only be run from the LiveCD."
@@ -43,8 +48,11 @@ nodes=$(get_ncns --exclude-pit) || exit 1
 # The get_ncns function should always give NCNs if its return code was 0, but better safe than sorry
 [[ -n ${nodes} ]] || err_exit "No NCNs found"
 
-for node in ${nodes}; do
-    run_ncn_tests "${node}" ncn-preflight-tests
-done
+test_urls=$(goss_endpoint_urls ncn-preflight-tests ${nodes}) || exit 1
 
-exit
+print_goss_json_results ${test_urls}
+rc=$?
+
+# This script does not exit with non-0 return code just for test failures
+[[ $rc -le 1 ]] && exit 0
+exit 1
diff --git a/goss-testing/automated/ncn-spire-healthchecks b/goss-testing/automated/ncn-spire-healthchecks
--- a/goss-testing/automated/ncn-spire-healthchecks
+++ b/goss-testing/automated/ncn-spire-healthchecks
@@ -22,19 +22,21 @@
 # ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 # OTHER DEALINGS IN THE SOFTWARE.
 
-# GOSS_BASE isn't set by default on the NCNs, just on LiveCD
-[[ -z ${GOSS_BASE} ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"
-
-export GOSS_LOG_BASE_DIR=/opt/cray/tests/install/logs
-
-source "${GOSS_BASE}/automated/run-ncn-tests.sh"
-
-# The create_tmpvars_file function is defined in run-ncn-tests.sh
-# It creates the temporary variables file and saves the path to it in the ${tmpvars} variable
-create_tmpvars_file || exit 1
+# Many functions and variables used in this script are defined/set/exported
+# in the run-ncn-tests.sh library
 
 echo $'\e[1;33m'Spire Health Checks$'\e[0m'
 echo $'\e[1;33m'-------------------$'\e[0m'
+
+# The run-ncn-tests.sh library is located in the same directory as the
+# current script. Using dirname like this could produce a relative path,
+# but that's fine, since we just want to source thie library script.
+# Note that this method is not infallible -- in particular, some symbolic
+# links can mess it up. But that won't be the case if this was installed
+# with the csm-testing RPM.
+source "$(dirname -- "$0")/run-ncn-tests.sh"
+
+tmpvars=$(create_goss_variable_file) || exit 1
 
 # Find the NCN node names and query the server endpoint
 # The get_ncns function is defined in run-ncn-tests.sh
@@ -43,9 +45,10 @@ nodes=$(get_ncns --exclude-pit) || exit 1
 # The get_ncns function should always give NCNs if its return code was 0, but better safe than sorry
 [[ -n ${nodes} ]] || err_exit "No NCNs found"
 
-for node in ${nodes} ; do
-    run_ncn_tests "${node}" "ncn-spire-healthchecks"
-done
+test_urls=$(goss_endpoint_urls ncn-spire-healthchecks ${nodes}) || exit 1
+
+print_goss_json_results ${test_urls}
+rc=$?
 
 # Specify the spire postgres clusters and call the postgres tests.
 # This only needs to be done once on the NCN that this script is
@@ -69,4 +72,6 @@ goss -g  "${GOSS_BASE}/tests/goss-k8s-postgres-leader.yaml" --vars "${tmpvars}" 
 echo $'\n\e[1;33m'-------------------$'\e[0m'
 echo $'\e[1;33m'Spire Health Checks Completed$'\e[0m\n'
 
-exit
+# This script does not exit with non-0 return code just for test failures
+[[ $rc -le 1 ]] && exit 0
+exit 1
