CASMINST-5025: Create more shared functions for automated scripts; prove methods for determing NCN lists (#345)
* Create more shared functions for automated scripts; improve methods for determing NCN lists
* Update kubectl path on PIT node
* Omit some k8s checks when PIT node booted
* Create common variable file
* Correct shellcheck issues

diff --git a/goss-testing/automated/ncn-healthcheck-storage b/goss-testing/automated/ncn-healthcheck-storage
--- a/goss-testing/automated/ncn-healthcheck-storage
+++ b/goss-testing/automated/ncn-healthcheck-storage
@@ -23,24 +23,28 @@
 # OTHER DEALINGS IN THE SOFTWARE.
 
 # GOSS_BASE isn't set by default on the NCNs, just on LiveCD
-[[ -z $GOSS_BASE ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"
+[[ -z ${GOSS_BASE} ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"
 
 export GOSS_LOG_BASE_DIR=/opt/cray/tests/install/logs
 
-source "$GOSS_BASE/automated/run-ncn-tests.sh"
+source "${GOSS_BASE}/automated/run-ncn-tests.sh"
 
 echo $'\e[1;33m'NCN Run-Time Checks$'\e[0m'
 echo $'\e[1;33m'-------------------$'\e[0m'
 
-# find the ncn node names and query the server endpoint
-if [ -f "/etc/dnsmasq.d/statics.conf" ]; then
-  cat /etc/dnsmasq.d/statics.conf | grep -ohE "ncn-[s]([0-9]{3})" | grep -v ncn-m001 | awk '!a[$0]++' | \
-    while read node ; do run_ncn_tests "$node" "9001" "ncn-healthcheck-storage" ; done
-else
-  cat /etc/hosts | grep -ohE "ncn-[s]([0-9]{3})" | awk '!a[$0]++' | while read node ; do \
-    run_ncn_tests "$node" "9001" "ncn-healthcheck-storage" ; \
-    run_ncn_tests "$node" "9006" "ncn-afterpitreboot-healthcheck-storage" ; \
-    done
-fi
+# Find the NCN node names and query the server endpoint
+# The get_ncns function is defined in run-ncn-tests.sh
+nodes=$(get_ncns --storage) || exit 1
+
+# The get_ncns function should always give NCNs if its return code was 0, but better safe than sorry
+[[ -n ${nodes} ]] || err_exit "No storage NCNs found"
+
+# Query the server endpoint
+for node in ${nodes} ; do
+	run_ncn_tests "${node}" "9001" "ncn-healthcheck-storage"
+	if ! is_pit_node ; then
+		run_ncn_tests "${node}" "9006" "ncn-afterpitreboot-healthcheck-storage"
+	fi
+done
 
 exit
diff --git a/goss-testing/automated/ncn-healthcheck-worker b/goss-testing/automated/ncn-healthcheck-worker
--- a/goss-testing/automated/ncn-healthcheck-worker
+++ b/goss-testing/automated/ncn-healthcheck-worker
@@ -23,34 +23,33 @@
 # OTHER DEALINGS IN THE SOFTWARE.
 
 # GOSS_BASE isn't set by default on the NCNs, just on LiveCD
-[[ -z $GOSS_BASE ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"
+[[ -z ${GOSS_BASE} ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"
 
 export GOSS_LOG_BASE_DIR=/opt/cray/tests/install/logs
 
-vars_file="$GOSS_BASE/vars/variables-ncn.yaml"
+vars_file="${GOSS_BASE}/vars/variables-ncn.yaml"
 
-source "$GOSS_BASE/automated/run-ncn-tests.sh"
+source "${GOSS_BASE}/automated/run-ncn-tests.sh"
 
 echo $'\e[1;33m'NCN Run-Time Checks$'\e[0m'
 echo $'\e[1;33m'-------------------$'\e[0m'
 
-# find the ncn node names and query the server endpoint
-if [ -f "/etc/dnsmasq.d/statics.conf" ]; then
-	cat /etc/dnsmasq.d/statics.conf | 
-	grep -ohE "ncn-[w]([0-9]{3})" | 
-	grep -v ncn-m001 | 
-	awk '!a[$0]++' |
-	while read node ; do
-		run_ncn_tests "$node" "9000" "ncn-healthcheck-worker"
-	done
-else
-	cat /etc/hosts | 
-	grep -ohE "ncn-[w]([0-9]{3})" | 
-	awk '!a[$0]++' | 
-	while read node ; do
-		run_ncn_tests "$node" "9000" "ncn-healthcheck-worker"
-		run_ncn_tests "$node" "9005" "ncn-afterpitreboot-healthcheck-worker"
-    done
+# The get_ncns function is defined in run-ncn-tests.sh
+if nodes=$(get_ncns --workers); then
+
+	# The get_ncns function should always give NCNs if its return code was 0, but better safe than sorry
+	if [[ -z ${nodes} ]]; then
+		print_error "No worker NCNs found"
+	else
+		# Query the server endpoints
+		for node in ${nodes} ; do
+			run_ncn_tests "${node}" "9000" "ncn-healthcheck-worker"
+			if ! is_pit_node ; then
+				run_ncn_tests "${node}" "9005" "ncn-afterpitreboot-healthcheck-worker"
+			fi
+		done
+	fi
+
 fi
 
 # Specify the switch passwords and call the switch BGP neighbors tests.
@@ -58,15 +57,19 @@ fi
 # executing on as the BGP status tests check all switches in
 # the cluster.
 # If explicit Aruba or Mellanox switch passwords were not provided, then go with SW_ADMIN_PASSWORD
-if [[ -z "$SW_ADMIN_PASSWORD" ]]; then
+if [[ -z ${SW_ADMIN_PASSWORD} ]]; then
 	echo "ERROR Management switch admin password must be provided via the SW_ADMIN_PASSWORD enviroment varaible"
 	echo "Example: export SW_ADMIN_PASSWORD='changeme'"
 	exit 1
 fi
 
+# The create_tmpvars_file function is defined in run-ncn-tests.sh
+# It creates the temporary variables file and saves the path to it in the ${tmpvars} variable
+create_tmpvars_file "${vars_file}" || exit 1
+
 echo $'\n\e[1;33m'---------------$'\e[0m'
 echo $'\e[1;33m'Switch BGP Neighbors$'\e[0m'
 echo "Test Name: goss-switch-bgp-neighbor-aruba-or-mellanox.yaml"
 echo "Description: Validates connection to the BGP neighbors of a switch. Check Admin Guide \"Check BGP Status and Reset Sessions\" for more details on how to fix this issue."
-goss -g "$GOSS_BASE/tests/goss-switch-bgp-neighbor-aruba-or-mellanox.yaml" --vars "$vars_file" validate --format documentation
+goss -g "${GOSS_BASE}/tests/goss-switch-bgp-neighbor-aruba-or-mellanox.yaml" --vars "${tmpvars}" validate --format documentation
 exit $?
diff --git a/goss-testing/automated/ncn-kubernetes-checks b/goss-testing/automated/ncn-kubernetes-checks
--- a/goss-testing/automated/ncn-kubernetes-checks
+++ b/goss-testing/automated/ncn-kubernetes-checks
@@ -23,59 +23,27 @@
 # OTHER DEALINGS IN THE SOFTWARE.
 
 # GOSS_BASE isn't set by default on the NCNs, just on LiveCD
-[[ -z $GOSS_BASE ]] && export GOSS_BASE=/opt/cray/tests/install/ncn
+[[ -z ${GOSS_BASE} ]] && export GOSS_BASE=/opt/cray/tests/install/ncn
 
 export GOSS_LOG_BASE_DIR=/opt/cray/tests/install/logs
 
-export GOSS_VARS=/tmp/goss-variables-$(date +%s)-temp.yaml
+source "${GOSS_BASE}/automated/run-ncn-tests.sh"
 
-source "$GOSS_BASE/automated/run-ncn-tests.sh"
-
-# files needed to run from livecd
+# file needed to run from livecd
 kube_creds=/root/.kube/config
-pit_file=/etc/pit-release
 
-if [ -f $pit_file ]; then
-  # running on a pit node
-  cat "$GOSS_BASE/vars/variables-livecd.yaml" > $GOSS_VARS
-else
-  # running on an NCN
-  cat "$GOSS_BASE/vars/variables-ncn.yaml" > $GOSS_VARS
-fi
-echo "" >> $GOSS_VARS
-
-# Add variables based on local system
-add_local_vars "$GOSS_VARS"
-
-if [ -f "/etc/dnsmasq.d/statics.conf" ]; then
-  k8s_nodes=$(cat /etc/dnsmasq.d/statics.conf | grep -ohE 'ncn-[mw]([0-9]{3})' | grep -v ncn-m001 | awk '!a[$0]++')
-else
-  k8s_nodes=$(cat /etc/hosts | grep -ohE 'ncn-[mw]([0-9]{3})' | awk '!a[$0]++')
-fi
-
-# add node names from statics.conf to temp variables file
-if [ `echo $k8s_nodes | wc -w` -ne 0 ];then
-  echo "" >> $GOSS_VARS
-  echo "k8s_nodes:" >> $GOSS_VARS
-  for node in $k8s_nodes; do
-    echo "  - $node" >> $GOSS_VARS
-  done
-else
-  echo "Node names could not be found in files! Exiting now."
-  exit 1
-fi
-
-if [ -f $pit_file ]; then
+# is_pit_node is defined in run-ncn-tests.sh
+if is_pit_node; then
   # running on a pit node
   echo $'\e[1;33m'PIT Node Kubernetes Checks$'\e[0m'
   echo $'\e[1;33m'--------------------------$'\e[0m'
-  if [ -f $kube_creds ]; then
+  if [[ -f ${kube_creds} ]]; then
     # run livecd local Kubernetes cluster tests
     k8s_local_tests
   else
     # We preface this warning with 'Total Tests:' to make it more visible, because the install documentation
     # has the user grep for that string to review the results of the tests.
-    echo $'\e[1;31m'Total Tests: WARNING: Unable to run local Kubernetes checks because $kube_creds does not exist$'\e[0m'
+    echo $'\e[1;31m'Total Tests: WARNING: Unable to run local Kubernetes checks because ${kube_creds} does not exist$'\e[0m'
     echo
   fi
 else
@@ -89,37 +57,46 @@ fi
 echo $'\e[1;33m'Master Node Kubernetes Checks$'\e[0m'
 echo $'\e[1;33m'-----------------------------$'\e[0m'
 
-# find the master node names and query the server endpoint
-if [ -f "/etc/dnsmasq.d/statics.conf" ]; then
-  nodes=$(cat /etc/dnsmasq.d/statics.conf | grep -ohE "ncn-m([0-9]{3})" | grep -v ncn-m001 | awk '!a[$0]++')
-  for node in $nodes ; do \
-    run_ncn_tests "$node" "8996" "ncn-kubernetes-tests-master" ; \
-  done
-else
-  nodes=$(cat /etc/hosts | grep -ohE "ncn-m([0-9]{3})" | awk '!a[$0]++')
-  for node in $nodes ; do \
-    run_ncn_tests "$node" "8996" "ncn-kubernetes-tests-master" ; \
-    run_ncn_tests "$node" "9007" "ncn-afterpitreboot-kubernetes-tests-master" ; \
-  done
+# The get_ncns function is defined in run-ncn-tests.sh
+if nodes=$(get_ncns --masters --exclude-pit); then
+
+	# The get_ncns function should always give NCNs if its return code was 0, but better safe than sorry
+	if [[ -z ${nodes} ]]; then
+		print_error "No master NCNs found"
+	else
+		# Query the server endpoints
+		for node in ${nodes} ; do
+			run_ncn_tests "${node}" "8996" "ncn-kubernetes-tests-master"
+			if ! is_pit_node ; then
+				run_ncn_tests "${node}" "9007" "ncn-afterpitreboot-kubernetes-tests-master"
+			fi
+		done
+	fi
+
 fi
+
 echo
 
 # worker nodes
 echo $'\e[1;33m'Worker Node Kubernetes Checks$'\e[0m'
 echo $'\e[1;33m'-----------------------------$'\e[0m'
 
-# find the worker node names and query the server endpoint
-if [ -f "/etc/dnsmasq.d/statics.conf" ]; then
-  nodes=$(cat /etc/dnsmasq.d/statics.conf | grep -ohE "ncn-w([0-9]{3})" | awk '!a[$0]++')
-  for node in $nodes ; do \
-    run_ncn_tests "$node" "8998" "ncn-kubernetes-tests-worker"; \
-  done
-else
-  nodes=$(cat /etc/hosts | grep -ohE "ncn-w([0-9]{3})" | awk '!a[$0]++')
-  for node in $nodes ; do \
-    run_ncn_tests "$node" "8998" "ncn-kubernetes-tests-worker" ; \
-    run_ncn_tests "$node" "9008" "ncn-afterpitreboot-kubernetes-tests-worker" ; \
-  done
+# The get_ncns function is defined in run-ncn-tests.sh
+if nodes=$(get_ncns --workers); then
+
+	# The get_ncns function should always give NCNs if its return code was 0, but better safe than sorry
+	if [[ -z ${nodes} ]]; then
+		print_error "No worker NCNs found"
+	else
+		# Query the server endpoints
+		for node in ${nodes} ; do
+			run_ncn_tests "${node}" "8998" "ncn-kubernetes-tests-worker"
+			if ! is_pit_node ; then
+				run_ncn_tests "${node}" "9008" "ncn-afterpitreboot-kubernetes-tests-worker"
+			fi
+		done
+	fi
+
 fi
 
 exit
diff --git a/goss-testing/automated/ncn-spire-healthchecks b/goss-testing/automated/ncn-spire-healthchecks
--- a/goss-testing/automated/ncn-spire-healthchecks
+++ b/goss-testing/automated/ncn-spire-healthchecks
@@ -23,25 +23,29 @@
 # OTHER DEALINGS IN THE SOFTWARE.
 
 # GOSS_BASE isn't set by default on the NCNs, just on LiveCD
-[[ -z $GOSS_BASE ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"
+[[ -z ${GOSS_BASE} ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"
 
 export GOSS_LOG_BASE_DIR=/opt/cray/tests/install/logs
 
-vars_file="$GOSS_BASE/vars/variables-ncn.yaml"
+source "${GOSS_BASE}/automated/run-ncn-tests.sh"
 
-source "$GOSS_BASE/automated/run-ncn-tests.sh"
+# The create_tmpvars_file function is defined in run-ncn-tests.sh
+# It creates the temporary variables file and saves the path to it in the ${tmpvars} variable
+create_tmpvars_file || exit 1
 
 echo $'\e[1;33m'Spire Health Checks$'\e[0m'
 echo $'\e[1;33m'-------------------$'\e[0m'
 
-# find the ncn node names and query the server endpoint
-if [ -f "/etc/dnsmasq.d/statics.conf" ]; then
-  cat /etc/dnsmasq.d/statics.conf | grep -ohE "ncn-[mw]([0-9]{3})" | grep -v ncn-m001 | awk '!a[$0]++' | \
-    while read node ; do run_ncn_tests "$node" "9003" "ncn-spire-healthchecks" ; done
-else
-  cat /etc/hosts | grep -ohE "ncn-[mw]([0-9]{3})" | awk '!a[$0]++' | while read node ; do run_ncn_tests "$node" "9003" \
-    "ncn-spire-healthchecks" ; done
-fi
+# Find the NCN node names and query the server endpoint
+# The get_ncns function is defined in run-ncn-tests.sh
+nodes=$(get_ncns --exclude-pit) || exit 1
+
+# The get_ncns function should always give NCNs if its return code was 0, but better safe than sorry
+[[ -n ${nodes} ]] || err_exit "No NCNs found"
+
+for node in ${nodes} ; do
+    run_ncn_tests "${node}" "9003" "ncn-spire-healthchecks"
+done
 
 # Specify the spire postgres clusters and call the postgres tests.
 # This only needs to be done once on the NCN that this script is
@@ -55,12 +59,12 @@ echo $'\n\e[1;33m'---------------$'\e[0m'
 echo $'\e[1;33m'NCN Spire Postgres Pods Running$'\e[0m'
 echo "Test Name: goss-k8s-postgres-pods-running"
 echo "Description: Validate that spire postgres pods are running."
-goss -g  "$GOSS_BASE/tests/goss-k8s-postgres-pods-running.yaml" --vars "$vars_file"  validate --format documentation
+goss -g  "${GOSS_BASE}/tests/goss-k8s-postgres-pods-running.yaml" --vars "${tmpvars}"  validate --format documentation
 echo $'\n\e[1;33m'---------------$'\e[0m'
 echo $'\e[1;33m'NCN Spire Postgres Pods Have a Leader$'\e[0m'
 echo "Test Name: goss-k8s-postgres-leader"
 echo "Description: Validate that spire postgres pods have a leader."
-goss -g  "$GOSS_BASE/tests/goss-k8s-postgres-leader.yaml" --vars "$vars_file" validate --format documentation
+goss -g  "${GOSS_BASE}/tests/goss-k8s-postgres-leader.yaml" --vars "${tmpvars}" validate --format documentation
 
 echo $'\n\e[1;33m'-------------------$'\e[0m'
 echo $'\e[1;33m'Spire Health Checks Completed$'\e[0m\n'
diff --git a/goss-testing/automated/ncn-storage-checks b/goss-testing/automated/ncn-storage-checks
--- a/goss-testing/automated/ncn-storage-checks
+++ b/goss-testing/automated/ncn-storage-checks
@@ -23,34 +23,31 @@
 # OTHER DEALINGS IN THE SOFTWARE.
 
 # GOSS_BASE isn't set by default on the NCNs, just on LiveCD
-[[ -z $GOSS_BASE ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"
+[[ -z ${GOSS_BASE} ]] && export GOSS_BASE="/opt/cray/tests/install/ncn"
 
 export GOSS_LOG_BASE_DIR=/opt/cray/tests/install/logs
 
-source "$GOSS_BASE/automated/run-ncn-tests.sh"
+source "${GOSS_BASE}/automated/run-ncn-tests.sh"
 
 echo $'\e[1;33m'Storage Node Automated Tests$'\e[0m'
 echo $'\e[1;33m'----------------------------$'\e[0m'
 
-# Find the storage node names
-if [ -f "/etc/dnsmasq.d/statics.conf" ]; then
-	storage_nodes=$(grep -oE 'ncn-s[0-9]{3}' /etc/dnsmasq.d/statics.conf | sort -u)
-else
-	storage_nodes=$(grep -oE 'ncn-s[0-9]{3}' /etc/hosts | sort -u)
+# The get_storage_ncns function is defined in run-ncn-tests.sh
+storage_nodes=$(get_ncns --storage) || exit 1
+
+# Excluding storage_nodes from the parenthesis because it contains newlines (which we do not want to include in the echo)
+echo "List of storage NCNs: "${storage_nodes}
+
+# The get_ncns function should always give NCNs if its return code was 0, but better safe than sorry
+[[ -n ${storage_nodes} ]] || err_exit "No storage nodes found"
+
+# It is important that we ran on ncn-s001, since some of the tests only run from that node
+if ! echo ${storage_nodes} | grep -q ncn-s001 ; then
+	print_error "ncn-s001 not listed among the storage nodes"
 fi
 
-echo "List of storage NCNs: $storage_nodes"
-
-if [[ -z $storage_nodes ]]; then
-	echo "ERROR: No storage nodes found"
-	exit 1
-elif ! echo $storage_nodes | grep -q ncn-s001 ; then
-	# It is important that we ran on ncn-s001, since some of the tests only run from that node
-	echo "ERROR: ncn-s001 not listed among the storage nodes"
-fi
-
-for nodename in $storage_nodes ; do
-	run_ncn_tests "$nodename" "8997" "ncn-storage-tests"
+for node in ${storage_nodes} ; do
+	run_ncn_tests "${node}" "8997" "ncn-storage-tests"
 done
 
 # We always exit 0 -- this does not indicate that the tests passed.
